version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    volumes:
      - ./backend:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 